# -*- coding: utf-8 -*-
"""TMod_UNET.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gua3E5B-EQ3cgDvRcljSaqj4EwHBONPQ

# 🧠 Evaluating the Effect of Multimodal MRI Channels on Automated 3D Glioma Segmentation using 3D U-Net

Project Aim : This project focuses on **brain tumor segmentation** using the **BRaTS 2020 dataset**, employing various MRI modality configurations to evaluate their effectiveness

Important Disclaimer: Generative AI has been used to assist in building some parts of the project especially in displaying results and evaluation section, and formatting in .md.

## Setting up the Environment
In order to execute the jupyter notebook you need first to obtain the kaggle API token. First you need to create a Kaggle Account and then obtain the API token from the website. Afterwards a JSON file is installed locally in the device. Then simply upload the JSON file in Google Colab and start executing the code below to invoke the token.
"""

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

#!/bin/bash
!kaggle datasets download andrewmvd/brain-tumor-segmentation-in-mri-brats-2015

!unzip brain-tumor-segmentation-in-mri-brats-2015.zip

!pip install nilearn

# General and Visualization Libraries
import os
import random
import numpy as np
import nibabel as nib
from matplotlib import pyplot as plt
from matplotlib.colors import ListedColormap
from skimage import data
from skimage.util import montage
import skimage.transform as skTrans
from skimage.transform import rotate
from skimage.transform import resize
from PIL import Image, ImageOps
from nilearn import plotting, image
import nibabel as nib

# Deep Learning Libraries
import keras
import tensorflow.keras.backend as K
from keras.callbacks import CSVLogger
import tensorflow as tf
from tensorflow.keras.utils import plot_model
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from tensorflow.keras.models import *
from tensorflow.keras.layers import *
from tensorflow.keras.optimizers import *
from tensorflow.keras.callbacks import ModelCheckpoint, ReduceLROnPlateau, EarlyStopping, TensorBoard
from sklearn.preprocessing import MinMaxScaler

"""## Data Visualization & Understanding
In this part of the notebook. The aim is to ensure and explore that we are abe to access the data in the dataset using the functionality provided by nibabel. Simply we will start defining the modailities of interest and the global parameters. First we define the relative path of the dataset file which contains all of the patient folders and the modalities as a list of strings. We then want to know that number of files in the dataset path. Given that data are explored previously, there are total of 371 files and within that there are two uneccessary files in .csv which contain the survival rates and patient information. These files does not contribute in the project so discarding them in neccessary to avoid future flaws.

All BraTS mutli-modal scans are presented in the dataset as a NiFTi file which are clinically used in medical images across various Magnetic Resonance Imaging machines. It captures the essential spatial information, but in order to access the data its required to perform data conversion from NifTI file into much computable and machine readable format Numpy. The dataset contains 369 patient files each of which has 5 MRI scans in .nii.gz format (flair, t1, t2, t1ce, seg).

"""

# Defining the global parameters
TRAIN_DATASET_PATH = '/content/MICCAI_BraTS2020_TrainingData/'
q_modalities = ['flair', 't1ce','t2','t1'] # Quad Modalities
t_modalities = ['flair', 't1ce', 't2'] # Triple Modalities
d_modalities = ['flair', 't1ce'] # Double Moalities

# The list of patient files
patients = os.listdir(TRAIN_DATASET_PATH)

# Get random number between 0 and 371
random_patient_index = random.randint(0, len(patients)-1)
random_patient = patients[random_patient_index]
rand_pat_data =  {}

# Get the data and the mask
for mod in q_modalities:
  rand_pat_data[mod] = nib.load(os.path.join(TRAIN_DATASET_PATH, random_patient,
                                             random_patient+'_'+mod+'.nii')).get_fdata()
test_mask = nib.load(os.path.join(TRAIN_DATASET_PATH, random_patient,
                                   random_patient+'_seg.nii')).get_fdata()

fig, axes = plt.subplots(2, 2, figsize=(10, 10)) # Create a 2x2 grid of subplots
titles = ['FLAIR', 'T1CE', 'T2', 'T1']
# Iterate through modalities and plot them on the grid
for i, (mod, title) in enumerate(zip(q_modalities, titles)):
    row = i // 2  # Calculate the row index
    col = i % 2   # Calculate the column index
    axes[row, col].imshow(rand_pat_data[mod][:, :, 80], cmap='gray')
    axes[row, col].set_title(title)

plt.tight_layout() # Adjust the spacing between subplots
plt.show() # Display the figureslice_w = 70

"""After visualizing random data wihtin the dataset, we want to further understand the nature of the segmentation mask generated in the dataset. Neccessary questions should be addressed ans answered prior developing a Deep Learning Model.
*   How many classes are present in the segmentation masks ?
*   What does reach encoding represent in a MRI image ?
*   Which type of encoding (data representation) used in masks ?
*   Are the labels in the mask are uniformly distrbuted, or there is a sparse dataset ?




"""

# List of patient directories; adjust filter if needed (e.g., only BraTS20 cases)
patients = [pat for pat in os.listdir(TRAIN_DATASET_PATH) if pat.startswith('BraTS20')]

# Get all of the unqiue segmentation values in the mask
unique_values = set()
for pat in patients:
    seg_path = os.path.join(TRAIN_DATASET_PATH, pat, f"{pat}_seg.nii")
    if os.path.exists(seg_path):
        mask = nib.load(seg_path).get_fdata()
        unique_values.update(np.unique(mask))

# Print the unique segmentation values
print("Unique segmentation values:", unique_values)

"""So we observe that there four unique labels in the ground-truth each are represented as floating point. Let's then observe the distribution of these labels across the ground-truth to further amplify our understanding on the data."""

# Initialize voxel counts for each class: 0=Background, 1=Necrotic, 2=Edema, 3=Enhancing Tumor
class_counts = {0: 0, 1: 0, 2: 0, 3: 0}

# Loop through each patient folder and update voxel counts from the segmentation mask
for pat in patients:
    seg_path = os.path.join(TRAIN_DATASET_PATH, pat, f"{pat}_seg.nii")
    if os.path.exists(seg_path):
        #Convert the mask from 4 to 3
        mask = nib.load(seg_path).get_fdata()
        mask[mask == 4] = 3
        for cls in class_counts.keys():
            class_counts[cls] += np.sum(mask == cls)

# Total number of voxels in all segmentation masks
total_voxels = sum(class_counts.values())

# Calculate percentage for each class
class_percentages = {cls: (count / total_voxels * 100) for cls, count in class_counts.items()}

# Define human-readable class labels
class_labels = ['Background', 'Necrotic', 'Edema', 'Enhancing Tumor']
counts = [class_counts[i] for i in range(4)]
percentages = [class_percentages[i] for i in range(4)]

"""In this part of the code we will focus on visualization of the class distribution. So first of all I want to visualize the distribution of malignant cells and healthy ones acrosss all of the masks values found in the dataset. Then I want to check the distribution of each of sub-regions of the tumors within the malignant cells."""

# Separate tumor classes (excluding background)
non_bg_labels = class_labels[1:]
non_bg_percentages = percentages[1:]

fig, axes = plt.subplots(2, 2, figsize=(14, 12))

# ============ BAR CHART: All Classes ============
axes[0, 0].bar(class_labels, percentages, color=['gray', 'blue', 'green', 'red'])
axes[0, 0].set_title('Class Distribution (All Classes)')
axes[0, 0].set_ylabel('Percentage of Voxels (%)')
axes[0, 0].grid(True, axis='y')

# ============ BAR CHART: Tumor Classes Only ============
axes[0, 1].bar(non_bg_labels, non_bg_percentages, color=['blue', 'green', 'red'])
axes[0, 1].set_title('Class Distribution (Tumor Classes Only)')
axes[0, 1].set_ylabel('Percentage of Voxels (%)')
axes[0, 1].grid(True, axis='y')

# ============ PIE CHART: All Classes ============
axes[1, 0].pie(
    percentages,
    labels=class_labels,
    autopct='%1.1f%%',
    startangle=90,
    colors=['gray', 'blue', 'green', 'red']
)
axes[1, 0].set_title('Class Distribution (All Classes)')

# ============ PIE CHART: Tumor Classes Only ============
axes[1, 1].pie(
    non_bg_percentages,
    labels=non_bg_labels,
    autopct='%1.1f%%',
    startangle=90,
    colors=['blue', 'green', 'red']
)
axes[1, 1].set_title('Class Distribution (Tumor Classes Only)')

plt.tight_layout()
plt.show()

"""Let's further observe the results of the intial study of the data.

1.   We notice that we are dealing with a sparse dataset, which means that there should be a further adjustments in model in order to mitigate the issues of sparse dataset. Either, we define a new informative loss function which accomodate the relevance of the data, or we simply add more scans of tumorous regions in the dataset. Since 98.9 % of the data in the dataset are labelled as background, while less than 2% is considered within the tumorous region.
2.   If we observe th distribution of tumrous sub-regions. We will notice that the occurene of necortic code and enhancing tumors are almost equivalent, while the exporsure of edema is three time greater than other sub-regions.


"""

# Show the slices
slice_index = 70
mask_slice = test_mask[:,:,slice_index]
flair_slice = rand_pat_data['flair'][:,:,slice_index]

# Assign colors for each of the slices
class_colors = ['black','blue', 'cyan','orange']
cmap = ListedColormap(class_colors)

class_labels = ['Backgorund','Necrotic','Edema','Enhancing Tumor']

plt.figure(figsize=(10,10))
plt.imshow(flair_slice,cmap='gray')
plt.imshow(mask_slice,cmap=cmap, alpha=0.5)

colorbar = plt.colorbar(ticks=[0,1,2,3])
colorbar.set_ticklabels(class_labels)

# Add a titile to the slice
plt.title(f'Flair with Mask Overlay, Slice = {slice_index}')
plt.show()

#
flair_niimg = nib.load(f"{TRAIN_DATASET_PATH}BraTS20_Training_002/BraTS20_Training_002_flair.nii")
mask_niimg = nib.load(f"{TRAIN_DATASET_PATH}BraTS20_Training_002/BraTS20_Training_002_seg.nii")

display = plotting.plot_anat(
    flair_niimg,
    title="Overlay: Flair with Mask",
    display_mode="ortho",  # Displays all three planes (axial, sagittal, coronal)
    dim=-1
)

display.add_overlay(mask_niimg, cmap="tab10", alpha=0.5)
plotting.show()

import nibabel as nib
import numpy as np
import matplotlib.pyplot as plt
from skimage.util import montage

# Load the MRI scan
img = nib.load(f"{TRAIN_DATASET_PATH}BraTS20_Training_002/BraTS20_Training_002_flair.nii")
data = img.get_fdata()

# Create a montage image from all slices
montage_image = montage(data)

plt.figure(figsize=(12, 12))
plt.imshow(montage_image, cmap='gray')
plt.axis('off')
plt.tight_layout()
plt.show()

"""After observing the dataset and understanding the possible issues that might be faced during the training procedure, we will start constructing the agents that will perform the segmentation procedure.

## Building Convolutional Neural Networks || 3D U-NETs
In this part of the code, the focus will be on building U-NET models in order to perform a comparitive analysis on the performance of the models across varing sizes of channels. The aim of this comparitive study is to understand the effect of additional incorportation of channels in the model performance. In order to build the model, tensorflow is used as the primary framework for developing such model. The architecture that has been chosen is U-NET which is one of the deep learning model architecture that excels in medical image analysis and segmentation. Further information regarding the UNET mdoel and the anatomy of such architecture is found in the following link : [U-Net: Convolutional Networks for Biomedical Image Segmentation](https://lmb.informatik.uni-freiburg.de/people/ronneber/u-net/)
"""

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Model

def build_unet(num_channels, NUM_CLASSES=4, dropout=0.2):
    inputs = layers.Input(shape=(128, 128, 128, num_channels))

    # Encoder Block 0
    conv0 = layers.Conv3D(16, (3, 3, 3), padding='same')(inputs)
    conv0 = layers.BatchNormalization()(conv0)
    conv0 = layers.ReLU()(conv0)
    conv0 = layers.Conv3D(16, (3, 3, 3), padding='same')(conv0)
    conv0 = layers.BatchNormalization()(conv0)
    conv0 = layers.ReLU()(conv0)

    pool1 = layers.MaxPooling3D(pool_size=(2, 2, 2))(conv0)

    # Encoder Block 1
    conv1 = layers.Conv3D(32, (3, 3, 3), padding='same')(pool1)
    conv1 = layers.BatchNormalization()(conv1)
    conv1 = layers.ReLU()(conv1)
    conv1 = layers.Conv3D(32, (3, 3, 3), padding='same')(conv1)
    conv1 = layers.BatchNormalization()(conv1)
    conv1 = layers.ReLU()(conv1)

    pool2 = layers.MaxPooling3D(pool_size=(2, 2, 2))(conv1)

    # Encoder Block 2
    conv2 = layers.Conv3D(64, (3, 3, 3), padding='same')(pool2)
    conv2 = layers.BatchNormalization()(conv2)
    conv2 = layers.ReLU()(conv2)
    conv2 = layers.Conv3D(64, (3, 3, 3), padding='same')(conv2)
    conv2 = layers.BatchNormalization()(conv2)
    conv2 = layers.ReLU()(conv2)

    pool3 = layers.MaxPooling3D(pool_size=(2, 2, 2))(conv2)

    # Encoder Block 3
    conv3 = layers.Conv3D(128, (3, 3, 3), padding='same')(pool3)
    conv3 = layers.BatchNormalization()(conv3)
    conv3 = layers.ReLU()(conv3)
    conv3 = layers.Conv3D(128, (3, 3, 3), padding='same')(conv3)
    conv3 = layers.BatchNormalization()(conv3)
    conv3 = layers.ReLU()(conv3)

    pool4 = layers.MaxPooling3D(pool_size=(2, 2, 2))(conv3)

    # Encoder Block 4
    conv4 = layers.Conv3D(256, (3, 3, 3), padding='same')(pool4)
    conv4 = layers.BatchNormalization()(conv4)
    conv4 = layers.ReLU()(conv4)
    conv4 = layers.Conv3D(256, (3, 3, 3), padding='same')(conv4)
    conv4 = layers.BatchNormalization()(conv4)
    conv4 = layers.ReLU()(conv4)

    pool5 = layers.MaxPooling3D(pool_size=(2, 2, 2))(conv4)

    # Bottleneck
    conv5 = layers.Conv3D(512, (3, 3, 3), padding='same')(pool5)
    conv5 = layers.BatchNormalization()(conv5)
    conv5 = layers.ReLU()(conv5)
    conv5 = layers.Conv3D(512, (3, 3, 3), padding='same')(conv5)
    conv5 = layers.BatchNormalization()(conv5)
    conv5 = layers.ReLU()(conv5)
    drop5 = layers.Dropout(dropout)(conv5)

    # Decoder Block 1
    up6 = layers.UpSampling3D(size=(2, 2, 2))(drop5)
    up6 = layers.Conv3D(256, (2, 2, 2), padding='same')(up6)
    up6 = layers.BatchNormalization()(up6)
    up6 = layers.ReLU()(up6)
    merge6 = layers.concatenate([conv4, up6])
    conv6 = layers.Conv3D(256, (3, 3, 3), padding='same')(merge6)
    conv6 = layers.BatchNormalization()(conv6)
    conv6 = layers.ReLU()(conv6)
    conv6 = layers.Conv3D(256, (3, 3, 3), padding='same')(conv6)
    conv6 = layers.BatchNormalization()(conv6)
    conv6 = layers.ReLU()(conv6)

    # Decoder Block 2
    up7 = layers.UpSampling3D(size=(2, 2, 2))(conv6)
    up7 = layers.Conv3D(128, (2, 2, 2), padding='same')(up7)
    up7 = layers.BatchNormalization()(up7)
    up7 = layers.ReLU()(up7)
    merge7 = layers.concatenate([conv3, up7])
    conv7 = layers.Conv3D(128, (3, 3, 3), padding='same')(merge7)
    conv7 = layers.BatchNormalization()(conv7)
    conv7 = layers.ReLU()(conv7)
    conv7 = layers.Conv3D(128, (3, 3, 3), padding='same')(conv7)
    conv7 = layers.BatchNormalization()(conv7)
    conv7 = layers.ReLU()(conv7)

    # Decoder Block 3
    up8 = layers.UpSampling3D(size=(2, 2, 2))(conv7)
    up8 = layers.Conv3D(64, (2, 2, 2), padding='same')(up8)
    up8 = layers.BatchNormalization()(up8)
    up8 = layers.ReLU()(up8)
    merge8 = layers.concatenate([conv2, up8])
    conv8 = layers.Conv3D(64, (3, 3, 3), padding='same')(merge8)
    conv8 = layers.BatchNormalization()(conv8)
    conv8 = layers.ReLU()(conv8)
    conv8 = layers.Conv3D(64, (3, 3, 3), padding='same')(conv8)
    conv8 = layers.BatchNormalization()(conv8)
    conv8 = layers.ReLU()(conv8)

    # Decoder Block 4
    up9 = layers.UpSampling3D(size=(2, 2, 2))(conv8)
    up9 = layers.Conv3D(32, (2, 2, 2), padding='same')(up9)
    up9 = layers.BatchNormalization()(up9)
    up9 = layers.ReLU()(up9)
    merge9 = layers.concatenate([conv1, up9])
    conv9 = layers.Conv3D(32, (3, 3, 3), padding='same')(merge9)
    conv9 = layers.BatchNormalization()(conv9)
    conv9 = layers.ReLU()(conv9)
    conv9 = layers.Conv3D(32, (3, 3, 3), padding='same')(conv9)
    conv9 = layers.BatchNormalization()(conv9)
    conv9 = layers.ReLU()(conv9)

    # Decoder Block 5
    up10 = layers.UpSampling3D(size=(2, 2, 2))(conv9)
    up10 = layers.Conv3D(16, (2, 2, 2), padding='same')(up10)
    up10 = layers.BatchNormalization()(up10)
    up10 = layers.ReLU()(up10)
    merge10 = layers.concatenate([conv0, up10])
    conv10 = layers.Conv3D(16, (3, 3, 3), padding='same')(merge10)
    conv10 = layers.BatchNormalization()(conv10)
    conv10 = layers.ReLU()(conv10)
    conv10 = layers.Conv3D(16, (3, 3, 3), padding='same')(conv10)
    conv10 = layers.BatchNormalization()(conv10)
    conv10 = layers.ReLU()(conv10)

    # Output Layer
    outputs = layers.Conv3D(NUM_CLASSES, (1, 1, 1), activation='softmax')(conv10)

    return Model(inputs=inputs, outputs=outputs)

"""## Loss Functions
In this part of the code, the aim is to define loss functions and metrics used in performing the following tasks. These mertics are used in order to perform comparative analysis on each version of the model. The implementation of the loss functions where obtained from the following github repository :  https://github.com/keras-team/keras/issues/9395
"""

# Dice loss as defined above for 4 classes
def dice_coef(y_true, y_pred, smooth=1.0):
    class_num = 4
    for i in range(class_num):
        y_true_f = K.flatten(y_true[:,:,:,:,i])
        y_pred_f = K.flatten(y_pred[:,:,:,:,i])
        intersection = K.sum(y_true_f * y_pred_f)
        loss = ((2. * intersection + smooth) / (K.sum(y_true_f) + K.sum(y_pred_f) + smooth))
        if i == 0:
            total_loss = loss
        else:
            total_loss = total_loss + loss

    total_loss = total_loss / class_num
    return total_loss

# Defining loss functions of dice per classes
def dice_coef_necrotic(y_true, y_pred, epsilon=1e-4):
    intersection = K.sum(K.abs(y_true[:,:,:,:,1] * y_pred[:,:,:,:,1]))
    return (2. * intersection) / (K.sum(K.square(y_true[:,:,:,:,1])) + K.sum(K.square(y_pred[:,:,:,1])) + epsilon)

def dice_coef_edema(y_true, y_pred, epsilon=1e-4):
    intersection = K.sum(K.abs(y_true[:,:,:,:,2] * y_pred[:,:,:,:,2]))
    return (2. * intersection) / (K.sum(K.square(y_true[:,:,:,:,2])) + K.sum(K.square(y_pred[:,:,:,2])) + epsilon)

def dice_coef_enhancing(y_true, y_pred, epsilon=1e-4):
    intersection = K.sum(K.abs(y_true[:,:,:,:,3] * y_pred[:,:,:,:,3]))
    return (2. * intersection) / (K.sum(K.square(y_true[:,:,:,:,3])) + K.sum(K.square(y_pred[:,:,:,3])) + epsilon)


# Defining Precision
def precision(y_true, y_pred):
        true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
        predicted_positives = K.sum(K.round(K.clip(y_pred, 0, 1)))
        precision = true_positives / (predicted_positives + K.epsilon())
        return precision


# Defining Sensitivity
def sensitivity(y_true, y_pred):
    true_positives = K.sum(K.round(K.clip(y_true * y_pred, 0, 1)))
    possible_positives = K.sum(K.round(K.clip(y_true, 0, 1)))
    return true_positives / (possible_positives + K.epsilon())


# Defining Specificity
def specificity(y_true, y_pred):
    true_negatives = K.sum(K.round(K.clip((1-y_true) * (1-y_pred), 0, 1)))
    possible_negatives = K.sum(K.round(K.clip(1-y_true, 0, 1)))
    return true_negatives / (possible_negatives + K.epsilon())

# Defining Tversky_loss
def tversky_loss(y_true, y_pred, alpha= 0.7, beta= 0.3, smooth=1e-6):
    y_true_f = K.flatten(y_true)
    y_pred_f = K.flatten(y_pred)
    # Compute TP, FP, FN
    TP = K.sum(y_true_f * y_pred_f)
    FP = K.sum(y_pred_f * (1-y_true_f))
    FN = K.sum((1-y_pred_f) * y_true_f)
    # Compute Tversky
    Tversky = (TP + smooth) / (TP + alpha*FN + beta*FP + smooth)
    return 1 - Tversky

# Defining Focal Loss
def focal_loss(y_true, y_pred, gamma=2.0, alpha=0.25):
    y_pred = K.clip(y_pred, K.epsilon(), 1.0 - K.epsilon())
    # Compute the focal loss term for each pixel and each class
    focal_loss_tensor = -y_true * alpha * K.pow(1 - y_pred, gamma) * K.log(y_pred)
    # Sum the loss over classes (typically the last axis)
    return K.sum(focal_loss_tensor, axis=-1)

# Example Compilation
chosen_mods = ['t1ce', 'flair', 't2']  # Example for a tri-modal setup
num_modalities = len(chosen_mods)

model = build_unet(num_channels=num_modalities)
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
    loss="categorical_crossentropy",
    metrics=['accuracy', tf.keras.metrics.MeanIoU(num_classes=4)]
)

model.summary()  # Check the input shape in the summary to verify it's (128, 128, 128, 3) for tri-modal.

"""
## Data Preprocessing

The preprocessing stage prepares the MRI scans for input into the segmentation model. Two main steps are applied:

1. **Normalization:**  
   The MRI scans are normalized using Min-Max scaling, which transforms the voxel intensity values into a range between 0 and 1. This helps ensure consistency across different scans and prevents intensity variation from affecting model performance.

2. **Brain Region Cropping:**  
   The scans are cropped to focus on the central brain region where the tumor is typically located. This reduces the input size, removes irrelevant background regions (such as the skull), and helps the model concentrate on the areas of interest.

These preprocessing steps are applied consistently across all input modalities to maintain uniformity and improve the effectiveness of the training process.

The next stage involves applying these preprocessing functions to the dataset before feeding the data into the training pipeline."""

# This function performs normalization which normalizes the voxel values between 0 and 1
def normalize_scan(scan, mask=None):
  scalar = MinMaxScaler()
  normalized = scalar.fit_transform(scan.flatten()[:, None]).reshape(scan.shape)
  return normalized

def crop_brain_region(volume):
    # Define cropping boundaries
    width_start, width_end = 56, 184
    height_start, height_end = 56, 184
    depth_start, depth_end = 13, 141

    # Crop volume
    cropped_volume = volume[width_start:width_end,
                            height_start:height_end,
                            depth_start:depth_end]
    return cropped_volume

"""## Splitting the Dataset
After preprocessing, the dataset is split into training, validation, and testing subsets. This step ensures that the model is trained on one portion of the data, validated on a separate portion to monitor performance during training, and finally tested on an unseen portion to evaluate the generalization ability of the model.
"""

TRAIN_DATASET_PATH = '/content/MICCAI_BraTS2020_TrainingData/'
patients = os.listdir(TRAIN_DATASET_PATH)

# Check if the strings in that patients starts with BRATS20
patients_veri = []
for pat in patients:
  if pat.startswith('BraTS20'):
    patients_veri.append(pat)
# Remove patient file number 355
patients_veri.remove('BraTS20_Training_355')

# Split the Path's into 70-20-10 spliy
train_ids, temp_ids = train_test_split(patients_veri, test_size=0.3, random_state=42)
val_ids, test_ids = train_test_split(temp_ids, test_size=1/3, random_state=42)

print(f"Train: {len(train_ids)}, Validation: {len(val_ids)}, Test: {len(test_ids)}")

# Display as a bar chart the split
import matplotlib.pyplot as plt

labels = ['Train', 'Validation', 'Test']
sizes = [len(train_ids), len(val_ids), len(test_ids)]
colors = ['blue', 'green', 'red']

plt.bar(labels, sizes, color=colors)
plt.xlabel('Dataset Split')
plt.ylabel('Number of Files')
plt.title('Dataset Split Distribution')
plt.grid(True)
plt.show()

"""## Data Generators
To efficiently handle the loading of large 3D MRI volumes during training, data generators are used. These generators load the data in batches, apply any necessary preprocessing (such as normalization and cropping), and feed the data into the model on the fly.

This approach prevents the need to load the entire dataset into memory at once, which is especially important when working with high-dimensional medical imaging data. The data generator is also responsible for applying data augmentation techniques during training to increase variability and help the model generalize better.

Separate generators are defined for the training, validation, and testing sets to ensure that:


*   Augmentation is applied only to the training data.

*   Validation and testing data remain unchanged for consistent evaluation.




"""

import tensorflow as tf
import numpy as np
import os
import nibabel as nib
from skimage.transform import resize
import matplotlib.pyplot as plt
from scipy import ndimage
import cv2

class DataGenerator(tf.keras.utils.Sequence):

    def __init__(self, list_IDs, chosen_mods=['flair', 't1ce', 't2'], batch_size=1,
                 dim=(128,128,128), n_classes=4, shuffle=True, augment=True):
        self.list_IDs = list_IDs
        self.chosen_mods = chosen_mods
        self.batch_size = batch_size
        self.dim = dim
        self.n_classes = n_classes
        self.shuffle = shuffle
        self.augment = augment
        self.indexes = np.arange(len(self.list_IDs))
        self.augment_count = 0
        self.augment_limit = 20 # Maximum Number of Samples to Augment
        self.on_epoch_end()

    def __len__(self):
        # Number of batches per epoch.
        return int(np.floor(len(self.list_IDs) / self.batch_size))

    def __getitem__(self, index):
        # Generate indexes of the batch
        indexes = self.indexes[index*self.batch_size:(index+1)*self.batch_size]
        batch_IDs = [self.list_IDs[k] for k in indexes]
        X, y = self.__data_generation(batch_IDs)
        return X, y

    def on_epoch_end(self):
        #Shuffles indexes after each epoch.
        if self.shuffle:
            np.random.shuffle(self.indexes)
        # Set the augment counter to 0 on end of every epoch
        self.augment_count = 0

    def load_mods(self, patient_folder, patient_id, chosen_mods):
        #Load and return a stacked 3D volume for the chosen modalities.
        mod_data = []
        for mod in chosen_mods:
            file_path = os.path.join(patient_folder, f"{patient_id}_{mod}.nii")
            img = nib.load(file_path)
            data = img.get_fdata()  # load data once
            mod_data.append(data)
        # Stack the data along the last dimension
        stacked_data = np.stack(mod_data, axis=-1)
        return stacked_data

    def __data_generation(self, batch_IDs):
        # Generates data containing batch_size samples with at least one tumor slice.
        num_channels = len(self.chosen_mods)
        X = np.empty((self.batch_size, *self.dim, num_channels), dtype=np.float32)
        y = np.empty((self.batch_size, *self.dim, self.n_classes), dtype=np.float32)
        valid_count = 0

        for i, ID in enumerate(batch_IDs):
            pat_path = os.path.join(TRAIN_DATASET_PATH, ID)
            # Call load_mods now works correctly because of self
            combined_data = self.load_mods(pat_path, ID, self.chosen_mods)
            mask_path  = os.path.join(pat_path, f"{ID}_seg.nii")

            if not os.path.exists(mask_path):
                print(f"⚠️ Skipping missing mask for patient: {ID}")
                continue

            # Load and process the mask
            mask = nib.load(mask_path).get_fdata()
            mask[mask == 4] = 3  # Fix segmentation labels if necessary
            mask = tf.one_hot(mask.astype(np.uint8), depth=self.n_classes)

            # Apply normalization and cropping (assuming these functions are defined)
            processed_data = normalize_scan(combined_data).astype(np.float32)
            processed_data = crop_brain_region(processed_data)
            processed_mask = crop_brain_region(mask)

            # Ensure at least one sample with a tumor is in the batch
            if np.any(processed_mask[..., 1:]):  # Check if tumor is present
              # If the augmentation is enabled and the limit is not exceeded, augment the sample
              if self.augment_count and self.augment < self.augment_limit:
                processed_data, processed_mask = self.augment_data(np.expand_dims(processed_data, axis=0),
                                                                   np.expand_dims(processed_mask, axis=0))
                # Remove the batch dimension added above
                processed_data = processed_data[0]
                processed_mask = processed_mask[0]
                self.augment_count += 1

              # Add the valid processed data to the batch
              X[valid_count] = processed_data
              y[valid_count] = processed_mask
              valid_count += 1
            else:
              print(f"⚠️ Skipping sample without tumor for patient: {ID}")

        # If no valid samples, return an empty batch to avoid crashes
        if valid_count == 0:
            print("⚠️ No tumor-containing data in batch, returning empty batch.")
            return np.zeros_like(X), np.zeros_like(y)

        return X[:valid_count], y[:valid_count]


    def augment_data(self, imgs, masks):
      """
      Apply real-time data augmentation to a batch of images and masks.

      Args:
        imgs: A NumPy array of images with shape (batch_size, D, H, W, C)
        masks: A NumPy array of masks with shape (batch_size, D, H, W, n_classes)

      Returns:
        Augmented imgs and masks with the same target shape.
      """
      # Create arrays to hold the augmented data
      augmented_imgs = np.empty_like(imgs)
      augmented_masks = np.empty_like(masks)

      # Process each sample in the batch individually
      for i in range(imgs.shape[0]):
        img = imgs[i]
        mask = masks[i]

        # Adding random Gaussian noise
        if np.random.rand() < 0.1:
            noise = np.random.normal(0, 0.01, img.shape)
            img = np.clip(img + noise, 0, 1)

        # Adding random translations (shift in x, y, and z)
        if np.random.rand() < 0.1:
            shift_x, shift_y, shift_z = np.random.randint(-10, 10, 3)
            # For a single sample, shape is (D, H, W, C)
            img = ndimage.shift(img, (shift_x, shift_y, shift_z, 0), mode='nearest')
            mask = ndimage.shift(mask, (shift_x, shift_y, shift_z, 0), mode='nearest')

        # Adding random scaling
        if np.random.rand() < 0.1:
            scale = np.random.uniform(0.9, 1.1)
            # Since each sample is 4D, use a tuple of 4 factors: (scale, scale, scale, 1)
            scale_factors = (scale, scale, scale, 1)
            img = ndimage.zoom(img, scale_factors, order=1)
            mask = ndimage.zoom(mask, scale_factors, order=0)

        # Adding random flips along the horizontal axis (axis=1)
        if np.random.rand() < 0.1:
            img = np.flip(img, axis=1)
            mask = np.flip(mask, axis=1)

        # Generate different views (e.g., rotation for axial, sagittal, coronal views)
        if np.random.rand() < 0.1:
            img, mask = self.generate_different_views(img, mask)

        # After augmentation, force the sample to resize back to the target shape.
        # The target shape for images is defined as self.dim + (num_channels,)
        target_shape_img = self.dim + (img.shape[-1],)
        # For masks, the target shape is self.dim + (mask.shape[-1],)
        target_shape_mask = self.dim + (mask.shape[-1],)

        if img.shape != target_shape_img:
            img = resize(img, target_shape_img, preserve_range=True, anti_aliasing=True).astype(np.float32)
        if mask.shape != target_shape_mask:
            mask = resize(mask, target_shape_mask, preserve_range=True, anti_aliasing=False).astype(np.float32)

        augmented_imgs[i] = img
        augmented_masks[i] = mask

      return augmented_imgs, augmented_masks


    def generate_different_views(self, img, mask):
        '''
        Generate different views (Axial, Sagittal, Coronal).
        '''
        axis_choice = np.random.choice([0, 1, 2])
        img = np.rot90(img, k=np.random.randint(1, 4), axes=(axis_choice, (axis_choice + 1) % 3))
        mask = np.rot90(mask, k=np.random.randint(1, 4), axes=(axis_choice, (axis_choice + 1) % 3))
        return img, mask

"""
## Model Training per Modality Configuration

To evaluate how different combinations of MRI modalities affect segmentation performance, the model is trained separately on three configurations: **di-modal**, **tri-modal**, and **quad-modal**.

For each configuration:
- The corresponding modalities are selected.
- Data generators are created for the training, validation, and testing sets using only the selected modalities.
- A U-Net model is built with an input shape that dynamically adapts to the number of selected channels.
- The model is compiled with a comprehensive set of evaluation metrics, including accuracy, mean IoU, Dice scores for each tumor region, as well as sensitivity, precision, and specificity.

During training:
- An early stopping callback is used to halt training if the validation loss does not improve for a defined number of epochs.
- A CSV logger records training progress for future analysis.

After training, the model is evaluated on a test set and the performance metrics are stored. Each model is saved separately for later comparison. This loop enables consistent and automated evaluation across all modality configurations."""

from gc import callbacks
modalities_config = {
    "di_modal": ["t1ce", "flair"],         # Example di-modal configuration
    "tri_modal": ["t1ce", "t2", "flair"],    # Example tri-modal configuration
    "quad_modal": ["t1", "t1ce", "t2", "flair"]  # Example quad-modal configuration
}
import tensorflow as tf

# Dictionary to store evaluation metrics for each configuration
results_summary = {}

# Loop over each modality configuration
for config_name, chosen_mods in modalities_config.items():
    print(f"\n=== Training model for configuration: {config_name} with modalities {chosen_mods} ===")

    # Define number of channels for this configuration
    num_channels = len(chosen_mods)

    # Create data generators for training and validation sets
    train_gen = DataGenerator(train_ids, chosen_mods=chosen_mods, batch_size=2,
                              dim=(128,128,128), n_classes=4, shuffle=True, augment=True)
    val_gen   = DataGenerator(val_ids, chosen_mods=chosen_mods, batch_size=2,
                              dim=(128,128,128), n_classes=4, shuffle=False, augment=False)

    # Build and compile the model with dynamic input shape
    model = build_unet(num_channels=num_channels, dropout=0.2, NUM_CLASSES=4)
    model.compile(
         optimizer=tf.keras.optimizers.Adam(learning_rate=0.0001),
         loss="categorical_crossentropy",
         metrics=['accuracy', tf.keras.metrics.MeanIoU(num_classes=4), dice_coef,
                  dice_coef_necrotic, dice_coef_edema, dice_coef_enhancing,
                  tversky_loss, focal_loss, sensitivity, precision, specificity]
    )

    # Print model summary for verification
    model.summary()

    # Train the model
    history = model.fit(train_gen,
                        epochs=20,
                        validation_data=val_gen,
                        callbacks=[tf.keras.callbacks.EarlyStopping(monitor='val_loss', patience=5, verbose=1, restore_best_weights=True),
                                   tf.keras.callbacks.CSVLogger(f'Training_2020_3D_UNet_{config_name}.log')],
                        verbose=1)

    # Evaluate the model on a test set
    test_gen = DataGenerator(test_ids, chosen_mods=chosen_mods, batch_size=2,
                             dim=(128,128,128), n_classes=4, shuffle=False, augment=False)
    eval_metrics = model.evaluate(test_gen, verbose=1)

    # Store the evaluation metrics
    results_summary[config_name] = eval_metrics

    # Save the trained model if desired
    model.save(f"{config_name}_model.h5")

# Print a summary of evaluation metrics
print("\nEvaluation Results Summary:")
for config, metrics in results_summary.items():
    print(f"{config}: {metrics}")

"""## Results Generation and Evaluation
After training a separate model for each modality configuration (di-modal, tri-modal, quad-modal), the notebook proceeds to evaluate and store the model performance:

Each trained model is evaluated on a separate test set that was not seen during training or validation. This ensures an unbiased assessment of the model's ability to generalize to new data.

The evaluation includes a set of predefined metrics:

Accuracy: Measures overall correct predictions.

Mean Intersection over Union (Mean IoU): Measures the overlap between the predicted segmentation and the ground truth across classes.

Dice Coefficients for specific tumor regions: necrotic core, edema, and enhancing tumor.

Sensitivity, Precision, and Specificity: Provides insight into how well the model detects true positives and avoids false positives or negatives.

Tversky Loss and Focal Loss: Loss functions used for additional evaluation beyond accuracy.

For each configuration:

The evaluation metrics are collected and stored in a results summary dictionary.

The trained model is saved in .h5 format with a filename indicating its configuration.

A training log file is generated using CSVLogger, which records the loss and metric values at each epoch.

At the end, a consolidated summary of evaluation results for all configurations is printed. This summary provides a direct comparison of how different modality setups influence model performance, helping to address the main research question regarding the impact of increasing the number of MRI input channels on segmentation quality.


"""

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

# List of configurations to compare.
configurations = ["di_modal", "tri_modal", "quad_modal"]

# We'll assume 'modalities_config' and the DataGenerator class are defined globally.
# Example: modalities_config = { "di_modal": ["t1ce", "flair"], ... }

fig, axes = plt.subplots(len(configurations), 3, figsize=(15, 5*len(configurations)))

for row, config in enumerate(configurations):
    print(f"Processing {config}...")

    # Load the model with proper custom objects (if necessary, include your custom metrics and loss functions).
    model = tf.keras.models.load_model(f"{config}_model.h5",
                custom_objects={
                    'dice_coef': dice_coef,
                    'dice_coef_necrotic': dice_coef_necrotic,
                    'dice_coef_edema': dice_coef_edema,
                    'dice_coef_enhancing': dice_coef_enhancing,
                    'tversky_loss': tversky_loss,
                    'focal_loss': focal_loss,
                    'sensitivity': sensitivity,
                    'precision': precision,
                    'specificity': specificity
                })

    # Create a test data generator for the chosen modalities.
    chosen_mods = modalities_config[config]
    test_gen = DataGenerator(test_ids, chosen_mods=chosen_mods, batch_size=1,
                             dim=(128,128,128), n_classes=4, shuffle=False, augment=False)

    # Retrieve one sample from the test generator.
    X_test, y_test = test_gen[0]

    # Run prediction.
    prediction = model.predict(X_test)
    prediction_labels = np.argmax(prediction, axis=-1)
    ground_truth_labels = np.argmax(y_test, axis=-1)

    # For visualization, choose a representative slice (e.g., middle slice in the depth axis).
    slice_idx = X_test.shape[1] // 2  # assuming depth is axis 1.
    # For display, select one of the input modality channels (say the first one).
    img_slice = X_test[0, :, :, slice_idx, 0]
    gt_slice = ground_truth_labels[0, :, :, slice_idx]
    pred_slice = prediction_labels[0, :, :, slice_idx]

    # Plot the input image (left column).
    axes[row, 0].imshow(img_slice, cmap='gray')
    axes[row, 0].set_title(f"{config} Input (Channel 1)")
    axes[row, 0].axis('off')

    # Plot the ground truth overlay (middle column).
    axes[row, 1].imshow(img_slice, cmap='gray')
    axes[row, 1].imshow(gt_slice, cmap='jet', alpha=0.5)
    axes[row, 1].set_title(f"{config} Ground Truth")
    axes[row, 1].axis('off')

    # Plot the prediction overlay (right column).
    axes[row, 2].imshow(img_slice, cmap='gray')
    axes[row, 2].imshow(pred_slice, cmap='jet', alpha=0.5)
    axes[row, 2].set_title(f"{config} Prediction")
    axes[row, 2].axis('off')

plt.suptitle("Qualitative Comparison of Segmentation Results", fontsize=20)
plt.tight_layout(rect=[0, 0, 1, 0.95])
plt.show()

import matplotlib.pyplot as plt

# Assume results_summary is a dictionary where each value is a list or array of evaluation metrics.
# Here, we assume that the Dice coefficient is at index 3 in the list returned by model.evaluate().
configs = list(results_summary.keys())
dice_scores = [results_summary[conf][3] for conf in configs]  # adjust the index if needed

plt.figure(figsize=(8, 6))
plt.bar(configs, dice_scores, color='skyblue')
plt.xlabel("Modality Configuration")
plt.ylabel("Dice Coefficient")
plt.title("Quantitative Comparison: Dice Coefficient by Configuration")
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Load CSV logs for the three configurations.
# Ensure that the CSV logs have columns labeled, for example, "epoch", "loss", "val_loss", "dice_coef", "val_dice_coef".
df_di   = pd.read_csv("Training_2020_3D_UNet_di_modal.log")
df_tri  = pd.read_csv("Training_2020_3D_UNet_tri_modal.log")
df_quad = pd.read_csv("Training_2020_3D_UNet_quad_modal.log")

# Plotting Convergence Curves: Training Loss and Dice coefficient over epochs.
fig, axes = plt.subplots(1, 2, figsize=(16, 6))

# --- Plot 1: Training Loss vs Epochs ---
axes[0].plot(df_di['epoch'], df_di['loss'], marker='o', label="Di-modal Loss")
axes[0].plot(df_tri['epoch'], df_tri['loss'], marker='o', label="Tri-modal Loss")
axes[0].plot(df_quad['epoch'], df_quad['loss'], marker='o', label="Quad-modal Loss")
axes[0].set_xlabel("Epoch")
axes[0].set_ylabel("Training Loss")
axes[0].set_title("Convergence of Training Loss")
axes[0].legend()
axes[0].grid(True)

# --- Plot 2: Training Dice Coefficient vs Epochs ---
axes[1].plot(df_di['epoch'], df_di['dice_coef'], marker='o', label="Di-modal Dice")
axes[1].plot(df_tri['epoch'], df_tri['dice_coef'], marker='o', label="Tri-modal Dice")
axes[1].plot(df_quad['epoch'], df_quad['dice_coef'], marker='o', label="Quad-modal Dice")
axes[1].set_xlabel("Epoch")
axes[1].set_ylabel("Dice Coefficient")
axes[1].set_title("Convergence of Dice Coefficient")
axes[1].legend()
axes[1].grid(True)

plt.tight_layout()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt

# Load the CSV files
df_di   = pd.read_csv("Training_2020_3D_UNet_di_modal.log")
df_tri  = pd.read_csv("Training_2020_3D_UNet_tri_modal.log")
df_quad = pd.read_csv("Training_2020_3D_UNet_quad_modal.log")

# Extract the final epoch metrics (assuming the last row holds final epoch values)
final_di   = df_di.iloc[-1]
final_tri  = df_tri.iloc[-1]
final_quad = df_quad.iloc[-1]

# Create a summary DataFrame for key metrics
summary = pd.DataFrame({
    "Configuration": ["di_modal", "tri_modal", "quad_modal"],
    "Loss": [final_di['loss'], final_tri['loss'], final_quad['loss']],
    "Accuracy": [final_di['accuracy'], final_tri['accuracy'], final_quad['accuracy']],
    "Dice": [final_di['dice_coef'], final_tri['dice_coef'], final_quad['dice_coef']],
    "Mean IoU": [final_di['mean_io_u_1'], final_tri['mean_io_u_2'], final_quad['mean_io_u_3']]
})

print("Numerical Comparison Summary:")
print(summary)

# Plotting comparisons for Dice and Mean IoU as bar charts.
fig, ax = plt.subplots(1, 2, figsize=(12, 6))

# Dice comparison bar chart
ax[0].bar(summary["Configuration"], summary["Dice"], color=["blue", "green", "red"])
ax[0].set_title("Dice Coefficient Comparison")
ax[0].set_ylabel("Dice Coefficient")
ax[0].set_xlabel("Modality Configuration")

# Mean IoU comparison bar chart
ax[1].bar(summary["Configuration"], summary["Mean IoU"], color=["blue", "green", "red"])
ax[1].set_title("Mean IoU Comparison")
ax[1].set_ylabel("Mean IoU")
ax[1].set_xlabel("Modality Configuration")

plt.tight_layout()
plt.show()

import tensorflow as tf
import numpy as np
import nibabel as nib
import os
ersky_loss, focal_loss, sensitivity, precision, specificity

# Example config map:
modalities_config = {
    "di_modal": ["t1ce", "flair"],
    "tri_modal": ["t1ce", "t2", "flair"],
    "quad_modal": ["t1", "t1ce", "t2", "flair"]
}

# Path to store NIfTI outputs
OUTPUT_DIR = "/content/NIFTI_predictions"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# We'll pick a single test sample index. You can pick any valid index from your test data generator.
test_sample_index = 1

for config_name, chosen_mods in modalities_config.items():
    print(f"\n=== Generating predictions for {config_name} ===")

    # 1. Load model
    # Include custom objects if you used them
    model = tf.keras.models.load_model(
        f"{config_name}_model.h5",
        custom_objects={
            # add your custom objects here if needed
            # "dice_coef": dice_coef,
            # "tversky_loss": tversky_loss,
            # "focal_loss": focal_loss,
            # "precision": precision,
            # "sensitivity": sensitivity,
            # "specificity": specificity
        }
    )

    # 2. Create a test data generator for chosen modalities
    test_gen = DataGenerator(
        test_ids,
        chosen_mods=chosen_mods,
        batch_size=1,              # Batch size 1 for easy indexing
        dim=(128,128,128),
        n_classes=4,
        shuffle=False,
        augment=False
    )

    # 3. Fetch one sample from the generator
    #    Adjust "test_sample_index" to pick any sample
    X_batch, y_batch = test_gen[test_sample_index]

    # 4. Run prediction
    prediction = model.predict(X_batch)  # shape: (1, D, H, W, num_classes)
    predicted_labels = np.argmax(prediction, axis=-1)  # shape: (1, D, H, W)

    # 5. Convert predictions to NIfTI
    # Remove batch dimension by indexing [0]
    pred_nii = nib.Nifti1Image(predicted_labels[0].astype(np.uint8), affine=np.eye(4))

    # 6. Convert the ground truth to NIfTI
    ground_truth = np.argmax(y_batch, axis=-1)    # shape (1, D, H, W)
    gt_nii = nib.Nifti1Image(ground_truth[0].astype(np.uint8), affine=np.eye(4))

    # 7. Save .nii files
    pred_nii_path = os.path.join(OUTPUT_DIR, f"{config_name}_prediction.nii")
    gt_nii_path = os.path.join(OUTPUT_DIR, f"{config_name}_ground_truth.nii")

    nib.save(pred_nii, pred_nii_path)
    nib.save(gt_nii, gt_nii_path)

    print(f"Saved prediction to: {pred_nii_path}")
    print(f"Saved ground truth to: {gt_nii_path}")

# Download the generated NIfTI files if you're on Google Colab
try:
    from google.colab import files
    for filename in os.listdir(OUTPUT_DIR):
        file_path = os.path.join(OUTPUT_DIR, filename)
        files.download(file_path)
except ImportError:
    pass  # Not running in Colab

import numpy as np
import tensorflow as tf
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay
import matplotlib.pyplot as plt

# Suppose these are the classes you have: 0=Background, 1=Necrotic, 2=Edema, 3=Enhancing
CLASS_LABELS = [0, 1, 2, 3]

# Example config map
modalities_config = {
    "di_modal": ["t1ce", "flair"],
    "tri_modal": ["t1ce", "t2", "flair"],
    "quad_modal": ["t1", "t1ce", "t2", "flair"]
}

for config_name, chosen_mods in modalities_config.items():
    print(f"\n=== Confusion Matrix for {config_name} ===")

    # 1. Load model
    model = tf.keras.models.load_model(
        f"{config_name}_model.h5",
        custom_objects={
            # if you have custom metrics/losses, list them here
            # 'dice_coef': dice_coef,
            # 'tversky_loss': tversky_loss,
            # ...
        }
    )

    # 2. Create a test data generator for chosen modalities
    test_gen = DataGenerator(
        test_ids,  # your test ids
        chosen_mods=chosen_mods,
        batch_size=1,       # so we can process samples individually
        dim=(128,128,128),
        n_classes=4,
        shuffle=False,
        augment=False
    )

    all_preds = []
    all_gts   = []

    # 3. Generate predictions for the entire test set
    for i in range(len(test_gen)):
        X_batch, y_batch = test_gen[i]
        pred_probs = model.predict(X_batch)     # shape: (1, D, H, W, num_classes)
        pred_labels = np.argmax(pred_probs, axis=-1)  # shape: (1, D, H, W)

        # Flatten volumes to 1D
        pred_flat = pred_labels.flatten()
        gt_flat   = np.argmax(y_batch, axis=-1).flatten()

        # Accumulate labels
        all_preds.append(pred_flat)
        all_gts.append(gt_flat)

    # Concatenate all predictions and ground truths
    all_preds = np.concatenate(all_preds, axis=0)
    all_gts   = np.concatenate(all_gts, axis=0)

    # 4. Compute confusion matrix (raw counts)
    cm = confusion_matrix(all_gts, all_preds, labels=CLASS_LABELS)

    # 5. Optional: Normalize the confusion matrix by true label counts
    # cm_norm = cm.astype('float') / cm.sum(axis=1, keepdims=True)
    # We'll use raw counts or you can choose to normalize

    # 6. Plot confusion matrix
    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=CLASS_LABELS)
    fig, ax = plt.subplots(figsize=(6, 6))
    disp.plot(ax=ax, cmap=plt.cm.Blues, values_format='g')
    ax.set_title(f"Confusion Matrix for {config_name}")
    plt.show()

    # If you want to see normalized confusion matrix, uncomment and plot cm_norm
    # disp_norm = ConfusionMatrixDisplay(confusion_matrix=cm_norm, display_labels=CLASS_LABELS)
    # fig, ax = plt.subplots(figsize=(6,6))
    # disp_norm.plot(ax=ax, cmap=plt.cm.Blues, values_format='.2f')
    # ax.set_title(f"Normalized Confusion Matrix for {config_name}")
    # plt.show()